### ISSUE TITLE
hi 作者你好 请教下如何解决 服务器使用魔法的呢

### ISSUE THREAD

**Issue by ruixule** [sotowang/chat-ai-public#1]

**Comment by sotowang** [comment]
1.我在代码里引入了代理
2.使用国外服务器

**Comment by ruixule** [comment]
> 1.我在代码里引入了代理
> 2.使用国外服务器

在case1的情况下，我直接使用阿云服务，也可以搞了？可以这样理解么

**Comment by sotowang** [comment]
> 

可以

> > 1.我在代码里引入了代理
> > 2.使用国外服务器
> 
> 在case1的情况下，我直接使用阿云服务，也可以搞了？可以这样理解么

可以
